{{- if .Values.registry.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ .Values.registry.server }}": {
          "auth": "{{ printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc }}"
        }
      }
    }
{{- end }}